In [3]:
pip install mysql-connector.python

Note: you may need to restart the kernel to use updated packages.


In [4]:
pip install mysql-connector.python

Note: you may need to restart the kernel to use updated packages.


In [42]:
import mysql.connector
db=mysql.connector.connect(
    host="localhost",
    user="root",
    password="root",
    database="booklist"
)
dbcursor=db.cursor()
dbcursor.execute("select book from bookdetail")
result=dbcursor.fetchall()
for i in result:
    print(i)

('Power of subconcious Mind',)
('Attitude is Everything',)
('Rich dad poor dad',)
('Power of subconcious Mind',)
('Attitude is Everything',)
('Rich dad poor dad',)


In [43]:
dbcursor=db.cursor()
dbcursor.execute("select book from bookdetail")
result=dbcursor.fetchall()

In [44]:
dbcursor.execute("show databases")

In [45]:
for i in dbcursor:
    print(i)
    

('a66',)
('alloc8_ajp_project',)
('assignment_schema',)
('booklist',)
('countries',)
('customer_order',)
('customer_orders',)
('dbe',)
('employee',)
('hr',)
('information_schema',)
('mysql',)
('performance_schema',)
('sakila',)
('sys',)
('temp_schema',)
('world',)


In [46]:
dbcursor.execute("USE booklist")  
dbcursor.execute("""
    CREATE TABLE IF NOT EXISTS bookdetail (
        Rating INT(20),
        Book VARCHAR(40),
        Price DECIMAL(16,2)
    )
""")
dbcursor.execute("SHOW TABLES")

for i in dbcursor:
    print(i)

('bookdetail',)


In [47]:
form="Insert into bookdetail(Rating,Book,Price) values(%s,%s,%s)"

data=[(4,"Power of subconcious Mind",99),
      (3,"Attitude is Everything",50),
      (5,"Rich dad poor dad",149),]
dbcursor.executemany(form,data)
db.commit()


In [3]:
import numpy as np

In [ ]:
c= np.aarange(10)
d= np.linespace(1,5,6)
print(c)
print(d)

In [6]:
a=np.array([7,9,9,2])
b=np.array([(7,9,9,2),(16,11,9,6)])
print(a.ndim)
print(a.itemsize)
print(a.dtype)
print(a.size*a.itemsize)
print(a.size)
print(b.shape)

1
8
int64
32
4
(2, 4)


In [7]:
b=np.array([(7,9,9,2),(16,11,9,6)])
print(b)
b=b.reshape(4,2)
print(b)

[[ 7  9  9  2]
 [16 11  9  6]]
[[ 7  9]
 [ 9  2]
 [16 11]
 [ 9  6]]


In [11]:
b=np.array([(7,9,9,2),(16,11,9,6)])
print(b[0,2]) #slicing the element from certain row and certain row column
print(b[0:,2]) #slicing element from all rows and certain column

9
[9 9]


In [21]:
e=np.array([7,9,9,2,16,11,96])
print(e.min()) # minimum values in array 
print(e.max()) #maximum value in array
print(e.sum()) #sum of array

2
96
150


In [22]:
a-np.array([7,9,9,2])
b=np.array([(7,9,9,2),(16,11,9,6)])
print(b.sum(axis=0))
print(b.sum(axis=1))
print(np.sqrt(a))
print(np.std(a))
print(np.exp(a))
print(np.log(a))
print(np.log10(a))

[23 20 18  8]
[27 42]
[2.64575131 3.         3.         1.41421356]
2.8613807855648994
[1.09663316e+03 8.10308393e+03 8.10308393e+03 7.38905610e+00]
[1.94591015 2.19722458 2.19722458 0.69314718]
[0.84509804 0.95424251 0.95424251 0.30103   ]


In [23]:
b=np.array([(7,9,9,2),(16,11,9,6)])
f=np.array([(1,2,3,4),(5,46,7,8)])
print(np.vstack((b,f)))  #vertical stack
print(np.hstack((b,f))) #horizontal stack
print(b.ravel())   #merging as single

[[ 7  9  9  2]
 [16 11  9  6]
 [ 1  2  3  4]
 [ 5 46  7  8]]
[[ 7  9  9  2  1  2  3  4]
 [16 11  9  6  5 46  7  8]]
[ 7  9  9  2 16 11  9  6]


In [24]:
threeDArray=np.array([
    [[1,2,3],[4,5,6]],
    [[-1,-2,-3],[-4,-5,-6]]
])
print(threeDArray)

[[[ 1  2  3]
  [ 4  5  6]]

 [[-1 -2 -3]
  [-4 -5 -6]]]


In [26]:
print(threeDArray.itemsize)
print(threeDArray.size)

8
12


In [27]:
nested_list=[[1,2,3],[4,5,6]]

In [29]:
for i in nested_list:
    for j in i:
        print(j)

1
2
3
4
5
6


In [30]:
for i in threeDArray.flatten():
    print(i)

1
2
3
4
5
6
-1
-2
-3
-4
-5
-6


In [31]:
threeDArray.flatten()
print(threeDArray)
threeDArray.ravel()
print(threeDArray)

[[[ 1  2  3]
  [ 4  5  6]]

 [[-1 -2 -3]
  [-4 -5 -6]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[-1 -2 -3]
  [-4 -5 -6]]]


In [32]:
zeros=np.zeros(5)
print(zeros)

[0. 0. 0. 0. 0.]


In [35]:
ones=np.ones(8)
print(ones)

[1. 1. 1. 1. 1. 1. 1. 1.]


In [36]:
ones=ones.astype(int)
print(ones)

[1 1 1 1 1 1 1 1]


In [41]:
ranges=np.arange(5,6,9.8)

In [42]:
print(ranges)

[5.]


In [48]:
linspace=np.linspace(3,6,10)
print(linspace)

[3.         3.33333333 3.66666667 4.         4.33333333 4.66666667
 5.         5.33333333 5.66666667 6.        ]


In [50]:
matrix=np.array([[76,34,89],[23,34,45]])
print(matrix)

[[76 34 89]
 [23 34 45]]


In [53]:
print(matrix+2)

[[78 36 91]
 [25 36 47]]


In [56]:
print(matrix.T)

[[76 23]
 [34 34]
 [89 45]]


In [57]:
 print(matrix[1,])

[23 34 45]


In [58]:
print("1-dimension")
full=np.full(10,5)
print(full)

print("2-dimension")
full=np.full((2,2),10)
print(full)
print("3-dimension")
full=np.full((2,5,4),5)
print(full)

1-dimension
[5 5 5 5 5 5 5 5 5 5]
2-dimension
[[10 10]
 [10 10]]
3-dimension
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]

 [[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]]


In [59]:
pythonlist1=[[76,34,89],[23,34,45]]
pythonlist2=[[76,34,89],[23,34,45]]

In [60]:
pythonlist1+pythonlist2

[[76, 34, 89], [23, 34, 45], [76, 34, 89], [23, 34, 45]]

In [70]:
matrix1=np.array([[1,2,3],[4,5,6]])
matrix2=np.array([[7,8,9],[10,11,12]])


In [62]:
print(matrix1-matrix2)

[[-6 -6 -6]
 [-6 -6 -6]]


In [74]:
marks=np.array([
       [87,90,89],[100,87,90],
       [94,77,90],[100,86,98]
])

In [76]:
print(marks.min())
print(marks.max())
print(marks.sum())
print(marks.mean())
print(marks.std())

77
100
1088
90.66666666666667
6.315765107165473


In [77]:
print(marks.min(axis=1))
print(marks.max(axis=1))
print(marks.sum(axis=1))
print(marks.mean(axis=1))
print(marks.std(axis=1))

[87 87 77 86]
[ 90 100  94 100]
[266 277 261 284]
[88.66666667 92.33333333 87.         94.66666667]
[1.24721913 5.55777733 7.25718035 6.18241233]


In [78]:
print(marks.min(axis=0))
print(marks.max(axis=0))
print(marks.sum(axis=0))
print(marks.mean(axis=0))
print(marks.std(axis=0))

[87 77 89]
[100  90  98]
[381 340 367]
[95.25 85.   91.75]
[5.35607132 4.84767986 3.63145976]


In [83]:
new_array=np.array([1,2,3])